apiVersion: v1
kind: Pod
metadata:
 name: pingmesh-server
 labels:
  name: pingmesh-server
spec:
 containers:
 - name: pingmesh-server
   image: pingmesh-server:1.0
   imagePullPolicy: Never
   ports:
    - name: http
      containerPort: 10009
---
kind: Service
apiVersion: v1
metadata:
  name: pms-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 10009
  selector:     
    name: pingmesh-server
